spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  sql:
    init:
      mode: always # 스프링 시작시 data.sql 항상 읽어오게 하는 옵션

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
        format_sql: true     # SQL 쿼리를 포맷해서 출력

    defer-datasource-initialization: true

mybatis:
  config-location: classpath:mybatis-config.xml

logging:
  level:
    root: info
    jdbc: debug

# log4jdbc 설정
log4jdbc:
  spylogdelegator.name: net.sf.log4jdbc.log.slf4j.Slf4jSpyLogDelegator