name: Prevent Sensitive Files Push

on: [push]

jobs:
  check-sensitive-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for sensitive files
        run: |
          # 아래의 if 조건문에 확인하고 싶은 파일이나 폴더를 추가합니다.
          # 'git ls-files --error-unmatch <경로>' 형식으로 추가하면 됩니다.
          # 예: 특정 폴더 추가하려면 'git ls-files --error-unmatch <폴더 경로>/*'
          #     특정 파일 추가하려면 'git ls-files --error-unmatch <파일 경로>'
          if git ls-files --error-unmatch study-app/DBconnectionSet.env || \
             git ls-files --error-unmatch study-app/study-developer/src/main/resources/wallet/*; then
          
             # 추가하려는 파일이나 폴더가 있으면 위 조건문에 ||로 연결하여 추가하세요.
             # 예시: git ls-files --error-unmatch path/to/another-sensitive-file || \
             #       git ls-files --error-unmatch path/to/another-sensitive-folder/*
          
            echo "Error: Sensitive files or folders are being pushed."
            exit 1